version: "3"
services:
  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
#    ports:
#      - "9090:9090"
    #depends_on:
    #  - example

#  example:
#    build: .
#    ports:
#      - "8080:8080"

  grafana:
    image: grafana/grafana:latest
    network_mode: "host"
    #ports:
    #  - "3000:3000"
    depends_on:
      - prometheus